// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUFZaAIUbMczhNSLgwhjCJyF2LiltAyX4',
    appId: '1:456567675872:web:fcbefe4dfffbfbf008a985',
    messagingSenderId: '456567675872',
    projectId: 'tawba-4c11b',
    authDomain: 'tawba-4c11b.firebaseapp.com',
    storageBucket: 'tawba-4c11b.firebasestorage.app',
    measurementId: 'G-WVR41XLB50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGQXkotigfe7-5QxF0Sglf07hcrRKupzk',
    appId: '1:456567675872:android:1b49e8316bed70d608a985',
    messagingSenderId: '456567675872',
    projectId: 'tawba-4c11b',
    storageBucket: 'tawba-4c11b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoHRi90OM5ofd-ZFn93ahfDsXJtxgNVEw',
    appId: '1:456567675872:ios:8f4ac765d1f7050908a985',
    messagingSenderId: '456567675872',
    projectId: 'tawba-4c11b',
    storageBucket: 'tawba-4c11b.firebasestorage.app',
    iosBundleId: 'com.example.tawbaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoHRi90OM5ofd-ZFn93ahfDsXJtxgNVEw',
    appId: '1:456567675872:ios:8f4ac765d1f7050908a985',
    messagingSenderId: '456567675872',
    projectId: 'tawba-4c11b',
    storageBucket: 'tawba-4c11b.firebasestorage.app',
    iosBundleId: 'com.example.tawbaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUFZaAIUbMczhNSLgwhjCJyF2LiltAyX4',
    appId: '1:456567675872:web:bc480999c705efb008a985',
    messagingSenderId: '456567675872',
    projectId: 'tawba-4c11b',
    authDomain: 'tawba-4c11b.firebaseapp.com',
    storageBucket: 'tawba-4c11b.firebasestorage.app',
    measurementId: 'G-9GBP0ZPMWL',
  );
}
